name: A simple demo
markdown: kramdown
safe: true
lsi: false
baseurl: ""

kramdown:
  auto_ids: false
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: true
  parse_span_html: true
  markdown, parse_block_html: true