name: A simple demo
markdown: kramdown
safe: true
lsi: false
pygments: true
baseurl: ""

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false