# Site settings
title: I.M. Hokie
email: your-email@domain.com
description: I am a Hokie and this is my ePortfolio."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 660000 #660000
  secondary: ff6600 #ff6600
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 439 Shanks Hall
  - line: Blacksburg, VA 24060

# Build settings
markdown: kramdown
permalink: pretty
